### ISSUE TITLE
Cannot read property 'startedDateTime' of undefined

### ISSUE THREAD

**Issue by NKjoep** [yarkeev/har-viewer#1]
Hello, great piece of software here! :) 

I wanted to report, sometimes when saving a har file from Chrome 54 and then importing it into har-viewer nothing happens.

I looked the console and:

``` log
file.js: 14 
Uncaught TypeError: Cannot read property 'startedDateTime' of undefined(…) 
       (anonymous function) @ file.js:14
```

So the issue is the first item within the har file has no `startedDateTime`, when this line runs we have the error:

``` js
// code...
  startPageTime = new Date(har.log.pages[0].startedDateTime).getTime(),
// code...
```

It would be nice to notify the user saying the given file is invalid.

**Comment by yarkeev** [comment]
@NKjoep, thank for report, fixed in version 0.0.11
